# Generated by Django 4.2.5 on 2023-10-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=60)),
                ('continent', models.CharField(max_length=50)),
                ('alpha2_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('image_file', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('portions', models.IntegerField(null=True)),
                ('diets', models.CharField(blank=True, max_length=70, null=True)),
                ('prepare_time', models.CharField(max_length=15)),
                ('cooking_time', models.CharField(max_length=15, null=True)),
                ('full_time', models.PositiveIntegerField(null=True)),
                ('nutrition_data', models.CharField(blank=True, max_length=150, null=True)),
                ('ingredients', models.TextField(null=True)),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StepsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('text_file', models.FileField(null=True, upload_to='recipes/')),
            ],
        ),
    ]
