# Generated by Django 4.2.5 on 2023-10-19 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Taster', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stepsfile',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stepsfile',
            name='recipeS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Taster.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Taster.country'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='images',
            field=models.ManyToManyField(related_name='recipes', to='Taster.foodimage'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Taster.stepsfile'),
        ),
        migrations.AddField(
            model_name='foodimage',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodimage',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Taster.recipe'),
        ),
    ]
