# Generated by Django 4.2.5 on 2023-10-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taster', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
